"""deleted database

Revision ID: 2be30aab03b1
Revises: 
Create Date: 2023-04-22 14:44:16.307600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be30aab03b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recycler',
    sa.Column('recycler_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('cans', sa.Integer(), nullable=True),
    sa.Column('plastic', sa.Integer(), nullable=True),
    sa.Column('glass', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('recycler_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recycler')
    # ### end Alembic commands ###
