"""updated table

Revision ID: 9da2d1712360
Revises: e3a29fc2b60e
Create Date: 2023-04-22 17:36:51.251405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da2d1712360'
down_revision = 'e3a29fc2b60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycler', sa.Column('cans', sa.Integer(), nullable=True))
    op.add_column('recycler', sa.Column('glass', sa.Integer(), nullable=True))
    op.add_column('recycler', sa.Column('plastic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recycler', 'plastic')
    op.drop_column('recycler', 'glass')
    op.drop_column('recycler', 'cans')
    # ### end Alembic commands ###
