"""created recycler table

Revision ID: a388afcf3f45
Revises: 
Create Date: 2023-04-22 16:52:50.777715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a388afcf3f45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('author_id', name='authors_pkey')
    )
    # ### end Alembic commands ###
